os: linux
dist: bionic
language: python
jobs:
  include:
    - Python 3.7 on Bionic
    - "3.7"

# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - python setup.py install
  - git clone https://github.com/astrochun/chun_codes.git chun_codes
  - cd chun_codes
  - python setup.py install
  - cd ..

script: pytest
