name: "Sphinx Docs Check"
on:
  push:
    paths:
    - 'docs/**'
    - 'Metallicity_Stack_Commons/**'
  pull_request:
    paths:
    - 'docs/**'
    - 'Metallicity_Stack_Commons/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout chun_codes
      uses: actions/checkout@v2
      with:
        repository: astrochun/chun_codes
        path: chun_codes
    - name: Install chun_codes
      run: |
        python3 setup.py develop
      working-directory: chun_codes
    - name: Sphinx build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"